import React from 'react';
import { Loader } from 'react-feather';
import styled from 'styled-components';

const Load = styled.span`
  /* ----------------------------------------------
* Generated by Animista on 2022-4-29 15:3:0
* Licensed under FreeBSD License.
* See http://animista.net/license for more info.
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

  /**
* ----------------------------------------
* animation rotate-center
* ----------------------------------------
*/
  @-webkit-keyframes rotate-center {
    0% {
      -webkit-transform: rotate(0);
      transform: rotate(0);
    }
    100% {
      -webkit-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }
  @keyframes rotate-center {
    0% {
      -webkit-transform: rotate(0);
      transform: rotate(0);
    }
    100% {
      -webkit-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }

  svg {
    animation: rotate-center 2s infinite;
    display: block;
    margin: auto;
    size: 10px;
  }
`;

function Loading({ size = 100 }: { size: number }): JSX.Element {
  return (
    <Load>
      <Loader size={size} />
    </Load>
  );
}

export default Loading;
